-- =====================================================================
-- WICKED — seed data
-- =====================================================================
-- Run after 0001_init.sql. Mirrors the mock data from src/data/store.ts so
-- the live UI shows the same catalogue. Re-run safe (uses ON CONFLICT).
-- =====================================================================

-- Categories
insert into public.categories (name, slug, sort_order) values
  ('Cleansers',       'cleansers',       1),
  ('Toners',          'toners',          2),
  ('Serums',          'serums',          3),
  ('Moisturisers',    'moisturisers',    4),
  ('Sunscreen / SPF', 'sunscreen-spf',   5),
  ('Masks',           'masks',           6),
  ('Eye Care',        'eye-care',        7),
  ('Sets / Bundles',  'sets-bundles',    8)
on conflict (slug) do nothing;

-- Products
-- Note: featured_image is the Unsplash hero used by the mock data. Replace
-- with real Supabase Storage URLs once product photography is uploaded.
insert into public.products (
  name, slug, description, short_description, brand, category, product_type,
  collection, tag, badge, price, compare_at_price, currency,
  images, featured_image, stock_quantity, is_active, is_featured,
  rating, review_count, skin_types, concerns, filters,
  benefits, ingredients, specs, variants, sizes, visual,
  long_description, care, delivery, returns, release_rank
) values
(
  'Hydrating Gel Cleanser', 'hydrating-gel-cleanser',
  'A cushiony daily gel cleanser that lifts sunscreen, oil, and city residue without leaving skin tight.',
  'pH-balanced cleanse', 'WICKED', 'Cleansers', 'Cleanser',
  'Daily Reset', 'pH-balanced cleanse', 'Best Seller',
  420, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  34, true, true, 4.9, 214,
  array['All skin types','Normal','Dry','Combination','Sensitive'],
  array['Dryness','Barrier Support'],
  array['Popular'],
  array['Removes daily buildup without a stripped finish','Leaves skin soft, fresh, and comfortable','Works as a morning cleanse or second cleanse at night'],
  array['Amino-acid cleansing system','Glycerin and panthenol support','pH-balanced daily formula'],
  array['Skin feel: fresh and soft','Best for: normal, dry, combination, and oily skin','Vegan formula','Dermatologist-tested'],
  array['Fragrance-free','Fresh mineral'], array['150ml'],
  jsonb_build_object('form','pump','accent','#8fd3c7','texture','water'),
  'Hydrating Gel Cleanser is the first step in the WICKED routine: clean enough for a fresh start, gentle enough for twice-daily use, and balanced so the rest of your skincare lands better.',
  'Massage onto damp skin for 30 to 60 seconds, rinse well, then follow with toner or serum.',
  'Fast South Africa delivery with protective recyclable packaging.',
  'Unopened skincare can be returned within 14 days. Contact support if anything arrives damaged.',
  12
),
(
  'Vitamin C Brightening Serum', 'vitamin-c-brightening-serum',
  'A lightweight vitamin C serum designed to brighten dull-looking skin and support a more even glow.',
  'Glow support', 'WICKED', 'Serums', 'Serum',
  'Targeted Actives', 'Glow support', 'Signature',
  760, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  18, true, true, 4.9, 188,
  array['Normal','Dry','Combination'],
  array['Dullness','Dark Spots'],
  array['Popular','Premium'],
  array['Helps dull-looking skin appear brighter','Layers smoothly under moisturiser and SPF','Adds a fresh, refined finish without heaviness'],
  array['Vitamin C derivative','Ferulic-inspired antioxidant support','Hyaluronic acid hydration'],
  array['Skin feel: light serum','Best for: uneven tone and dullness','Use: morning','Always finish with SPF'],
  array['Original','Sensitive'], array['30ml'],
  jsonb_build_object('form','dropper','accent','#f0b35b','texture','citrus'),
  'This daily brightening serum gives the routine a sharp, polished finish without sticky residue. It layers cleanly under moisturiser and SPF, making it easy to use every morning.',
  'Apply two to three drops after cleansing. Use SPF every morning while using brightening actives.',
  'Ships in light-protective packaging with tracked delivery.',
  'Unopened skincare can be returned within 14 days. Used actives are final sale for hygiene reasons.',
  11
),
(
  'Barrier Repair Moisturiser', 'barrier-repair-moisturiser',
  'A plush ceramide moisturiser that seals in hydration and leaves skin calm, cushioned, and ready for the day.',
  'Ceramide comfort', 'WICKED', 'Moisturisers', 'Moisturiser',
  'Barrier Support', 'Ceramide comfort', 'Best Seller',
  640, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  22, true, true, 4.8, 246,
  array['Normal','Dry','Combination','Sensitive'],
  array['Barrier Support','Dryness','Redness'],
  array['Popular','Premium'],
  array['Supports a stronger-feeling skin barrier','Comforts dryness without a greasy film','Pairs well with retinoids, acids, and brightening serums'],
  array['Ceramide complex','Squalane and glycerin','Soft-touch cream texture'],
  array['Skin feel: cushioned','Best for: dry, normal, and combination skin','Use: morning or night','Fragrance-free option'],
  array['Original','Rich'], array['50ml'],
  jsonb_build_object('form','jar','accent','#d6bf8d','texture','cream'),
  'Barrier Repair Moisturiser is the comfort layer in the WICKED lineup. It supports skin that feels dry, overworked, or reactive, while keeping the finish clean enough for morning use.',
  'Apply after serum. Use a generous layer at night when skin needs extra comfort.',
  'Ships with tamper-evident packaging and tracked delivery.',
  'Unopened moisturisers can be returned within 14 days. Damaged items are replaced quickly.',
  10
),
(
  'Niacinamide Refining Serum', 'niacinamide-refining-serum',
  'A refining serum for visible pores, uneven texture, and excess shine that still respects the skin barrier.',
  'Texture reset', 'WICKED', 'Serums', 'Serum',
  'Targeted Actives', 'Texture reset', 'New',
  690, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  20, true, false, 4.8, 137,
  array['Normal','Oily','Combination'],
  array['Pores & Texture','Oil Control','Acne & Breakouts'],
  array['New','Premium'],
  array['Helps skin look smoother and more refined','Supports balanced-looking shine','Comfortable under moisturiser, SPF, and makeup'],
  array['Niacinamide-led formula','Zinc PCA support','Hydrating base'],
  array['Skin feel: fast-absorbing gel serum','Best for: combination and oily skin','Use: morning or night','Avoid layering with too many actives at once'],
  array['Original'], array['30ml'],
  jsonb_build_object('form','dropper','accent','#b9c7ff','texture','silk'),
  'Niacinamide Refining Serum is built for skin that wants clarity without harshness. The texture is fast-absorbing, easy to layer, and designed for consistent use.',
  'Apply one to two pumps after toner. Follow with moisturiser.',
  'Fast South Africa delivery with recyclable protective wrap.',
  'Unopened serums can be returned within 14 days.',
  9
),
(
  'Mineral Daily SPF', 'mineral-daily-spf',
  'A mineral daily SPF with a soft, breathable finish for the final step of every morning routine.',
  'Daily protection', 'WICKED', 'Sunscreen / SPF', 'Sunscreen',
  'Barrier Support', 'Daily protection', 'Signature',
  520, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  27, true, true, 4.7, 171,
  array['All skin types','Sensitive'],
  array['Sun Protection','Dark Spots'],
  array['Popular'],
  array['Daily broad-spectrum mineral protection','Soft finish that works under makeup','Designed to layer over active skincare'],
  array['Mineral UV filters','Hydrating emollient base','Sheer and tinted options'],
  array['Skin feel: soft cream','Best for: daily morning use','Reapply during prolonged sun exposure','SPF is the last step before makeup'],
  array['Sheer','Tinted'], array['50ml'],
  jsonb_build_object('form','tube','accent','#f4de7d','texture','sun'),
  'Mineral Daily SPF keeps protection clear and practical. The finish is modern, the feel is comfortable, and the formula is made to sit cleanly over serums and moisturiser.',
  'Apply generously every morning. Reapply every two hours with direct sun exposure.',
  'Ships with heat-conscious handling during warm weather.',
  'Unopened SPF can be returned within 14 days.',
  8
),
(
  'Overnight Recovery Mask', 'overnight-recovery-mask',
  'A leave-on night mask for skin that needs a calm, replenished look by morning.',
  'Night repair', 'WICKED', 'Masks', 'Mask',
  'Barrier Support', 'Night repair', 'Limited',
  580, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  12, true, false, 4.9, 122,
  array['Normal','Dry','Sensitive'],
  array['Barrier Support','Dryness','Dullness'],
  array['Premium'],
  array['Locks in hydration overnight','Helps tired-looking skin appear smoother by morning','Comforts skin after active-heavy routines'],
  array['Beta-glucan support','Ceramide-rich feel','Cushion gel-cream texture'],
  array['Skin feel: cocooning gel cream','Best for: dry, stressed, or dull-looking skin','Use: two to four nights weekly','Leave-on formula'],
  array['Original'], array['60ml'],
  jsonb_build_object('form','jar','accent','#8fb7a2','texture','night'),
  'Overnight Recovery Mask is a low-effort reset for tired-looking skin. Use it as the final evening step when your routine needs extra comfort and visible softness.',
  'Apply a thin layer as the final evening step. Rinse in the morning if desired.',
  'Ships with protective packaging and tracking.',
  'Unopened masks can be returned within 14 days.',
  7
),
(
  'Peptide Eye Cream', 'peptide-eye-cream',
  'A focused eye cream for a smoother, more awake look without heavy slip or sparkle.',
  'Smooth focus', 'WICKED', 'Eye Care', 'Eye Cream',
  'Barrier Support', 'Smooth focus', 'New',
  720, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  15, true, false, 4.8, 94,
  array['All skin types'],
  array['Fine Lines','Dryness','Dullness'],
  array['New','Premium'],
  array['Hydrates the delicate eye area','Helps the eye area look smoother and less tired','Airless pump keeps the formula clean and controlled'],
  array['Peptide complex','Caffeine support','Light-refining hydration'],
  array['Skin feel: lightweight cream','Best for: tired-looking eye area','Use: morning or night','Ophthalmologist-tested'],
  array['Original'], array['15ml'],
  jsonb_build_object('form','pump','accent','#c4b7ff','texture','peptide'),
  'Peptide Eye Cream keeps the eye step efficient: a small airless pump, a clean texture, and support for dryness and fine-looking lines around the eye area.',
  'Tap a rice-grain amount around the orbital bone. Avoid direct contact with eyes.',
  'Ships in protective packaging sized for small-format skincare.',
  'Unopened eye care can be returned within 14 days.',
  6
),
(
  'Gentle Exfoliating Toner', 'gentle-exfoliating-toner',
  'A gentle resurfacing toner that keeps texture polished without making the routine feel aggressive.',
  'Smooth tone', 'WICKED', 'Toners', 'Toner',
  'Daily Reset', 'Smooth tone', 'Signature',
  480, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  24, true, true, 4.7, 152,
  array['Normal','Oily','Combination'],
  array['Pores & Texture','Dullness','Dark Spots'],
  array['Popular'],
  array['Helps refine uneven-looking texture','Preps skin for serum without harsh scrubbing','Designed for two to four uses per week'],
  array['PHA and lactic acid blend','Aloe and glycerin base','No physical scrub particles'],
  array['Skin feel: fresh liquid','Best for: dullness and texture','Use: evening','Do not use on broken or irritated skin'],
  array['Original','Sensitive'], array['120ml'],
  jsonb_build_object('form','pump','accent','#f7a98b','texture','acid'),
  'Gentle Exfoliating Toner is built for controlled clarity. It gives skin a smoother look over time while leaving room for hydration and barrier support.',
  'Apply after cleansing at night. Start slowly, then follow with moisturiser.',
  'Ships with leak-conscious closure and tracking.',
  'Unopened toners can be returned within 14 days.',
  5
),
(
  'Clarifying Clay Mask', 'clarifying-clay-mask',
  'A creamy clay mask that helps absorb excess oil while keeping skin comfortable and balanced.',
  'Oil control', 'WICKED', 'Masks', 'Mask',
  'Daily Reset', 'Oil control', 'Best Seller',
  560, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  19, true, true, 4.8, 163,
  array['Oily','Combination'],
  array['Oil Control','Acne & Breakouts','Pores & Texture'],
  array['Popular'],
  array['Helps skin look clearer and less shiny','Creamy texture avoids a tight, cracked finish','Ideal for T-zone use or a full-face weekly reset'],
  array['Kaolin and bentonite clay','Zinc support','Comfort-focused cream base'],
  array['Skin feel: creamy clay','Best for: oily and combination skin','Use: one to three times weekly','Rinse-off formula'],
  array['Original'], array['75ml'],
  jsonb_build_object('form','jar','accent','#b7c0a6','texture','clay'),
  'Clarifying Clay Mask is a reset for congested-looking skin. It uses a creamy base so the mask feels polished, not chalky or punishing.',
  'Apply a thin layer for 8 to 10 minutes, then rinse before the mask fully dries.',
  'Ships in reinforced packaging to protect jars in transit.',
  'Unopened masks can be returned within 14 days.',
  4
),
(
  'Glow Renewal Skincare Set', 'glow-renewal-skincare-set',
  'A three-step WICKED routine with cleanser, brightening serum, and barrier moisturiser.',
  'Complete routine', 'WICKED', 'Sets / Bundles', 'Set',
  'Glow Sets', 'Complete routine', 'Sale',
  1490, 1690, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  10, true, false, 4.9, 201,
  array['All skin types','Normal','Dry','Combination'],
  array['Dullness','Dryness','Barrier Support'],
  array['Premium','Sale','Popular'],
  array['Simple three-step routine','Includes bestselling daily essentials','Premium gift-ready presentation'],
  array['Hydrating Gel Cleanser','Vitamin C Brightening Serum','Barrier Repair Moisturiser'],
  array['Routine: cleanse, treat, moisturise','Best for: dullness and dehydration','Value set','Gift-ready black carton'],
  array['Morning glow','Night repair'], array['3-piece set'],
  jsonb_build_object('form','set','accent','#d6bf8d','texture','set'),
  'Glow Renewal Skincare Set takes the guesswork out of starting WICKED. Cleanse, treat, and seal with three formulas that work together and look sharp on the shelf.',
  'Use the cleanser morning and night, vitamin C in the morning, and moisturiser as the final comfort step.',
  'Free delivery applies automatically to this set.',
  'Sets may be returned unopened within 14 days. Partial set returns are not accepted.',
  3
),
(
  'Hyaluronic Acid Serum', 'hyaluronic-acid-serum',
  'A hydration serum that gives skin a plump, fresh look and makes the rest of the routine feel smoother.',
  'Hydration layer', 'WICKED', 'Serums', 'Serum',
  'Targeted Actives', 'Hydration layer', 'Limited',
  620, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  13, true, false, 4.7, 118,
  array['All skin types','Dry','Sensitive'],
  array['Dryness','Fine Lines','Barrier Support'],
  array['Premium'],
  array['Boosts visible hydration','Softens the look of dehydration lines','Pairs easily with vitamin C, niacinamide, and moisturiser'],
  array['Multi-weight hyaluronic acid','Glycerin hydration','Panthenol comfort'],
  array['Skin feel: dewy serum','Best for: all skin types','Use: morning or night','Apply to slightly damp skin'],
  array['Original'], array['30ml'],
  jsonb_build_object('form','dropper','accent','#85c7ff','texture','hydration'),
  'Hyaluronic Acid Serum is the quiet workhorse in the WICKED lineup. It layers under any moisturiser, adds slip without stickiness, and helps skin look freshly hydrated.',
  'Apply to slightly damp skin, then seal with moisturiser.',
  'Fast South Africa delivery with tracking.',
  'Unopened serums can be returned within 14 days.',
  2
),
(
  'Daily Reset Toner', 'daily-reset-toner',
  'A no-sting daily toner that refreshes skin after cleansing and prepares it for serum.',
  'Balance step', 'WICKED', 'Toners', 'Toner',
  'Daily Reset', 'Balance step', 'New',
  450, null, 'ZAR',
  array['https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88'],
  'https://images.unsplash.com/photo-1701056035595-58d01e6e50f1?auto=format&fit=crop&w=2400&q=88',
  28, true, false, 4.6, 86,
  array['All skin types','Sensitive'],
  array['Redness','Barrier Support','Dryness'],
  array['New'],
  array['Refreshes skin after cleansing','Preps skin for better serum glide','Comfortable enough for daily use'],
  array['Centella-inspired calm','Betaine hydration','Alcohol-free feel'],
  array['Skin feel: fresh liquid','Best for: all skin types','Use: morning or night','No added fragrance'],
  array['Original'], array['120ml'],
  jsonb_build_object('form','pump','accent','#a8dcc8','texture','balance'),
  'Daily Reset Toner keeps the routine calm and clean. It is the simple bridge between cleansing and treatment, built for skin that wants hydration without extra noise.',
  'Press into clean skin with hands or apply with a reusable cotton pad.',
  'Ships with secure closure and tracking.',
  'Unopened toners can be returned within 14 days.',
  1
)
on conflict (slug) do nothing;

-- Promo code from local logic (WICKED10 = 10% off)
insert into public.promo_codes (code, type, value, is_active)
values ('WICKED10', 'percentage', 10, true)
on conflict (code) do nothing;
